package bootpay

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"mime/multipart"
	"net/url"
	"os"
	"path/filepath"
	"strconv"
)

// ProductModule handles product-related operations
type ProductModule struct {
	api *CommerceApi
}

// List retrieves product list
func (m *ProductModule) List(params *ProductListParams) (map[string]interface{}, error) {
	query := ""
	if params != nil {
		queryParams := url.Values{}
		if params.Page > 0 {
			queryParams.Set("page", strconv.Itoa(params.Page))
		}
		if params.Limit > 0 {
			queryParams.Set("limit", strconv.Itoa(params.Limit))
		}
		if params.Keyword != "" {
			queryParams.Set("keyword", params.Keyword)
		}
		if params.Type > 0 {
			queryParams.Set("type", strconv.Itoa(params.Type))
		}
		if params.PeriodType != "" {
			queryParams.Set("period_type", params.PeriodType)
		}
		if params.SAt != "" {
			queryParams.Set("s_at", params.SAt)
		}
		if params.EAt != "" {
			queryParams.Set("e_at", params.EAt)
		}
		if params.CategoryCode != "" {
			queryParams.Set("category_code", params.CategoryCode)
		}
		if len(queryParams) > 0 {
			query = "?" + queryParams.Encode()
		}
	}
	return m.api.Get("products" + query)
}

// Products retrieves product list (V1 Mall API)
// GET /v1/products
// page/limit default to 1/20 when unset; other values are sent only when provided.
// ⚠️ keyword is not read by the server (v1/products_controller#index) — it uses only
// page/limit/category_id/ex_uid/sort and silently ignores keyword. Kept for compatibility.
func (m *ProductModule) Products(params *MallProductListParams) (map[string]interface{}, error) {
	if params == nil {
		params = &MallProductListParams{}
	}
	queryParams := url.Values{}
	page := params.Page
	if page <= 0 {
		page = 1
	}
	limit := params.Limit
	if limit <= 0 {
		limit = 20
	}
	queryParams.Set("page", strconv.Itoa(page))
	queryParams.Set("limit", strconv.Itoa(limit))
	if params.CategoryId != "" {
		queryParams.Set("category_id", params.CategoryId)
	}
	if params.ExUid != "" {
		queryParams.Set("ex_uid", params.ExUid)
	}
	if params.Sort != "" {
		queryParams.Set("sort", params.Sort)
	}
	if params.Keyword != "" {
		queryParams.Set("keyword", params.Keyword)
	}
	if params.Type > 0 {
		queryParams.Set("type", strconv.Itoa(params.Type))
	}
	if params.PeriodType != "" {
		queryParams.Set("period_type", params.PeriodType)
	}
	if params.SAt != "" {
		queryParams.Set("s_at", params.SAt)
	}
	if params.EAt != "" {
		queryParams.Set("e_at", params.EAt)
	}
	if params.CategoryCode != "" {
		queryParams.Set("category_code", params.CategoryCode)
	}
	return m.api.getWithHeaders("products?"+queryParams.Encode(), commerceMallHeaders(params.UserJwt, params.IdempotencyKey))
}

// Create creates a new product with optional images (manager scope)
// POST /v1/products
// With imagePaths the request is sent as multipart/form-data, otherwise as JSON.
// ⚠️ Rails does not accept repeated `images` as an array — files must be indexed
// as images[0], images[1], ...
func (m *ProductModule) Create(product CommerceProduct, imagePaths []string) (map[string]interface{}, error) {
	headers := commerceRoleHeaders("manager", "")

	if len(imagePaths) == 0 {
		return m.api.postWithHeaders("products", product, headers)
	}

	fields, err := productMultipartFields(product)
	if err != nil {
		return nil, err
	}

	body := &bytes.Buffer{}
	writer := multipart.NewWriter(body)
	for key, value := range fields {
		if err := writer.WriteField(key, value); err != nil {
			return nil, err
		}
	}

	for index, imagePath := range imagePaths {
		file, err := os.Open(imagePath)
		if err != nil {
			return nil, err
		}

		part, err := writer.CreateFormFile(fmt.Sprintf("images[%d]", index), filepath.Base(imagePath))
		if err != nil {
			file.Close()
			return nil, err
		}
		if _, err = io.Copy(part, file); err != nil {
			file.Close()
			return nil, err
		}
		file.Close()
	}

	if err := writer.Close(); err != nil {
		return nil, err
	}

	// Content-Type must keep the boundary generated by the writer (FormDataContentType)
	return m.api.postMultipart("products", body, writer.FormDataContentType(), headers)
}

// productMultipartFields flattens a product into multipart form fields.
// Arrays/objects are sent as JSON strings, scalars as plain strings (omitempty is respected
// by round-tripping through the struct's JSON representation).
func productMultipartFields(product CommerceProduct) (map[string]string, error) {
	raw, err := json.Marshal(product)
	if err != nil {
		return nil, err
	}
	flat := map[string]interface{}{}
	if err := json.Unmarshal(raw, &flat); err != nil {
		return nil, err
	}

	fields := map[string]string{}
	for key, value := range flat {
		switch v := value.(type) {
		case string:
			fields[key] = v
		default:
			encoded, err := json.Marshal(v)
			if err != nil {
				return nil, err
			}
			fields[key] = string(encoded)
		}
	}
	return fields, nil
}

// CreateSimple creates a new product without images (JSON only, manager scope)
func (m *ProductModule) CreateSimple(product CommerceProduct) (map[string]interface{}, error) {
	return m.api.postWithHeaders("products", product, commerceRoleHeaders("manager", ""))
}

// Detail retrieves product details
func (m *ProductModule) Detail(productId string) (map[string]interface{}, error) {
	return m.api.Get(fmt.Sprintf("products/%s", productId))
}

// ProductDetail retrieves product details (V1 Mall API)
// GET /v1/products/{product_id}
// userJwt is the member JWT (attached as Bootpay-User-JWT only when present).
// idempotencyKey is auto-generated when empty.
func (m *ProductModule) ProductDetail(productId string, userJwt string, idempotencyKey string) (map[string]interface{}, error) {
	return m.api.getWithHeaders(fmt.Sprintf("products/%s", productId), commerceMallHeaders(userJwt, idempotencyKey))
}

// LookupProduct retrieves product details (V1 Mall API)
// GET /v1/products/{product_id}
// ⚠️ Same uri and behaviour as ProductDetail — kept because existing callers may rely on the name.
// New code should use ProductDetail.
func (m *ProductModule) LookupProduct(productId string, userJwt string, idempotencyKey string) (map[string]interface{}, error) {
	return m.api.getWithHeaders(fmt.Sprintf("products/%s", productId), commerceMallHeaders(userJwt, idempotencyKey))
}

// Update updates product information (manager scope)
// PUT /v1/products/{product_id}
// Only changed values need to be sent. ⚠️ category_id presence is how the server detects
// an unset intention — be careful when including it.
func (m *ProductModule) Update(product CommerceProduct) (map[string]interface{}, error) {
	if product.ProductId == "" {
		return nil, fmt.Errorf("product_id is required")
	}
	return m.api.putWithHeaders(fmt.Sprintf("products/%s", product.ProductId), product, commerceRoleHeaders("manager", ""))
}

// Status changes product display/sale status (manager scope)
// PUT /v1/products/{product_id}/status
// ⚠️ Stock is changed through Update, not here.
func (m *ProductModule) Status(params ProductStatusParams) (map[string]interface{}, error) {
	if params.ProductId == "" {
		return nil, fmt.Errorf("product_id is required")
	}
	return m.api.putWithHeaders(fmt.Sprintf("products/%s/status", params.ProductId), params, commerceRoleHeaders("manager", params.IdempotencyKey))
}

// Delete deletes a product (manager scope)
// DELETE /v1/products/{product_id}
func (m *ProductModule) Delete(productId string) (map[string]interface{}, error) {
	return m.api.deleteWithHeaders(fmt.Sprintf("products/%s", productId), nil, commerceRoleHeaders("manager", ""))
}
